sudo : true
group: edge
dist : xenial
language: cpp

compiler:
- clang
- gcc

install:
  - sudo apt install flex bison g++

script:
    - ./configure && make  && make testsim
    - make testsim-tls
    - make testsim-mcf
